<?php
/** @var $block \Magento\Catalog\Block\Product\View */

$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockObject = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_product->getId());
$currentStockQty = $stockObject->getQty();

$minQtyAllowed = $stockObject->getMinSaleQty();

#show drop down for fractional fabric products
$showDropdown = false;
if ($minQtyAllowed < 1) {
    $showDropdown = true;
}

// non-quote products
if ($_product->isSaleable() && !$_product->getEnableRequestforquote()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <?php if ($showDropdown): ?>
                          <div class="field qty">
                              <label class="label" for="qty"><span>Qty</span></label>
                              <select name="qty" id="qty" title="Qty" class="input-text qty dropdown" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                                     <option value>Choose amount...</option>
                                     <?php $i = .5 ;
                                       while ($i <= $currentStockQty) { ?>
                                          <option value="<?php echo $i; ?>"><?php echo $i . ' yard cut'; ?></option>
                                          <?php $i = $i + .5; ?>
                                       <?php } ?>
                              </select>

                          </div>
                  <?php else: ?>
                      <div class="field qty">
                      <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                      <div class="control">
                          <input type="number"
                                 name="qty"
                                 id="qty"
                                 value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                                 title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                 class="input-text qty"
                                 data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                 />
                      </div>
                  <?php endif; ?>
        </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "catalogAddToCart": {
                    "bindSubmit": true
                }
            }
        }
    </script>
<?php endif; ?>

<?php // extending Quote extension's addtocart.phtml ?>

<?php $_helper = $this->helper('Magento\Catalog\Helper\Output');?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $requestforquote_helper=$this->helper('Milople\Requestforquote\Helper\Requestforquote');?>
<?php $textcolor = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/color'); ?>
<?php $enable_enquire_button = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/show_enquiry_button'); ?>
<?php $enquiry_form_title = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/enquiry_form_title'); ?>
<?php $countryCollection = $requestforquote_helper->getCountries(); ?>
<?php $baseurl = $this->helper('Milople\Requestforquote\Helper\Data')->getBaseUrl() . 'requestforquote/index/save'; ?>
<?php $tnc = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/show_terms_and_conditions');?>
<?php $url=$requestforquote_helper->getMediaURL(); ?>
<style>
.flex{
	display: flex;
	align-items: center;
}
.call_img{
	float:left;
	padding-right:2%;
	width: 10%;
}
.label_text{
	color:<?php echo  $textcolor ?>;
	word-wrap: break-word;
	font-size: 16px;
	float: left;
	width: 88%;"
}
.checkbox_style{
		margin-top: 5px !important;
}
</style>
<?php if ($_product->isSaleable() && $_product->getEnableRequestforquote()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
		<?php $enableflag = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/license_status_group/status'); ?>
		<?php $callimage = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/upload_image_id'); ?>
		<?php $p_url = $_product->getProductUrl(); ?>
		<!--call for price condition-->
		<?php if((($_product->getEnableRequestforquote() and $enableflag == 'specific_products') || ($enableflag == 'all_products')) and $requestforquote_helper->isValidCustomer()):?>
		<?php $buttonTitle = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/call_us_on_contact_number'); ?>
        <div class="actions flex">
            <div class="call_img">
				<img src="<?php echo $url ?><?php echo $callimage?>" alt="Call Image" height="50" width="50">
			</div>
			<div class="label_text">
				<?php /* @escapeNotVerified */ echo $buttonTitle ?>
			</div>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
		<!--Show Enquire Now Condition-->
			<?php if($enable_enquire_button == true):?>
				<div style="margin-top:5%;">
					<button type="button"
						id="enquire_now_btn"
						title="<?php echo $block->escapeHtml(__('Enquire Now')); ?>"
						class="action tocart primary">
							<span><?php /* @escapeNotVerified */ echo $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/tag_setting_group/enquire_now_button_text'); ?></span>
					</button>
					<div id="popup-mpdal" style="display:none;width:90%">
						<form id="enquiry_form">
							<input type="text" name="productname" id="pname" style="display:none;"/>
							<input type="text" name="producturl" id="purl" style="display:none;"/>
							Name:
							<input type="text" name="firstname" id="name" required/><br><br>
							E-mail:
							<input type="email" name="email" id="email" required/><br><br>
							<label for="country_name">Country : </label>
							<input id="country_name" name="country_name" type="text" list="country" required/><br><br>
								<datalist id="country">
									<?php foreach( $countryCollection as $label ): ?>
										<?php if($label['label']==' '): ?>
											<?php continue; ?>
										<?php endif; ?>
										<option value="<?php print_r($label['label']);?>">
									<?php endforeach; ?>
								</datalist>
							Phone Number:<br>
							<input type="number" name="phone_number" id="phone"><br><br>
							Description:<br>
							<textarea name="description" id="description" required/></textarea><br>
							<?php if($tnc==true):?>
								<input type="checkbox" id="chk_tnc"name="termsandconditions" class="checkbox_style" required/> I agree to the terms and conditions
							<?php endif; ?>
						</form>
					</div>
				</div>
			<?php endif; ?>
		<div class="product-social-links"></div>
		<?php else: ?>
		<div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
		<?php endif; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '<?php echo $enquiry_form_title;?> for <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>',
                buttons: [{
					text: $.mage.__('Clear'),
                    class: '',
                    click: function () {
						document.getElementById("name").value='';
						document.getElementById("email").value='';
						document.getElementById("country_name").value='';
						document.getElementById("phone").value='';
						document.getElementById("description").value='';
					}
				},{
                    text: $.mage.__('Submit'),
                    class: '',
                    click: function () {
						var formData=new FormData(jQuery('#enquiry_form')[0]);
						var name=document.getElementById("name").value;
						var email=document.getElementById("email").value;
						var country=document.getElementById("country_name").value;
						var phone=document.getElementById("phone").value;
						var description=document.getElementById("description").value;
						var product_url='<?php echo $p_url;?>';
						var product_name_popup = '<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>';
						document.getElementById("pname").value=product_name_popup;
						document.getElementById("purl").value=product_url;
						var done;
						formData.append("name",name );
						formData.append("email", email);
						formData.append("country", country);
						formData.append("phone", phone);
						formData.append("description", description);
						formData.append("pname",document.getElementById("pname").value);
						formData.append("purl",document.getElementById("purl").value);
						if(<?php echo $tnc;?>==true)
						{
							var chk_tnc=document.getElementById("chk_tnc").checked;;
							if(chk_tnc==true)agree='done';
						}
						if(<?php echo $tnc;?>==false)
						{
							agree='done';
						}
						if(name!='' && email!='' && country!='' && description!='' && agree=='done'){
						$.ajax({
							url: "<?php echo $baseurl ?>",
							data:formData ,
							showLoader: true,
							cache: false,
							type: 'post',
							processData: false,
							contentType: false,
							}).done(function(data){
								$( "aside" ).removeClass( "_show" );
								$("div.modals-overlay").remove();
								document.getElementById("description").value='';
						});
						agree=null;
						this.closeModal();
						}

                    }
                }]
            };
            var popup = modal(options, $('#popup-mpdal'));
            $("#enquire_now_btn").on('click',function(){
                $("#popup-mpdal").modal("openModal");
            });

        }
    );
</script>
<?php endif; ?>
