<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
?>
<?php $item = $block->getItem(); ?>
<?php $product = $item->getProduct();?>
<?php $requestforquote_helper=$this->helper('Milople\Requestforquote\Helper\Requestforquote');?>
<?php $enableflag = $this->helper('Milople\Requestforquote\Helper\Data')->getConfig('requestforquote/license_status_group/status'); ?>							
<?php $product_requestforquote=$requestforquote_helper->isProductEnabledForrequestforquote($product->getId()); ?>
<!--call for price condition-->
<?php if(($product_requestforquote=='No' and $enableflag =='specific_products' and $requestforquote_helper->isValidCustomer()) || ($enableflag != 'disable' and $requestforquote_helper->isValidCustomer() == false) || $enableflag == 'disable'):?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
<?php endforeach;?>
<?php endif; ?>