<?php

$cards = $this->getCards();
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');

if (empty($cards)): ?>
<div class="message info empty">
  <span><?php echo $block->escapeHtml(__('You do not have any saved cards yet.')); ?></span>
</div>
<?php else: ?>
  <div class="table-wrapper stripe-payments">
    <table class="data table table-order-items history saved-cards" id="my-orders-table">
      <caption class="table-caption"><?php echo $block->escapeHtml(__('Saved Cards')); ?></caption>
      <thead>
        <tr>
          <th scope="col" class="col cards" colspan="3">
            <?php echo $block->escapeHtml(__('Cards')); ?>
          </th>
          <th scope="col" class="col actions"><?php echo $block->escapeHtml(__('Actions')); ?></th>
        </tr>
      </thead>
      <tbody>
  <?php foreach ($cards as $card): ?>
      <tr>
        <td data-th="Brand" class="col brand">
          <span class="type <?php echo $card->brand; ?>">
            <?php echo $block->cardType($card->brand); ?>
          </span>
        </td>
        <td data-th="Last 4" class="col last4">
          ****&nbsp;<?php echo $card->last4; ?>
        </td>
        <td data-th="Expires" class="col exp">
          <?php echo $card->exp_month; ?>/<?php echo $card->exp_year; ?>
        </td>
        <td data-th="Actions" class="col actions">
          <a href="delete/<?php echo $card->id; ?>" class="stripe-payments delete-card">
            <?php echo $block->escapeHtml(__('Delete')); ?>
          </a>
        </td>
      </tr>
  <?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php endif; ?>

<?php if (!$block->config->getSaveCards()) { return; } ?>
<br>

<form class="form new-saved-card" action="save/" method="post" id="payment_form_stripe_payments_payment">
  <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
  <fieldset class="fieldset payment-method stripe-new stripe-payments">
    <legend class="legend"><span><?php echo $block->escapeHtml(__('Add a new saved card')); ?></span></legend>
    <br>

<?php if ($this->verifyBillingAddress()): ?>

  <?php if ($this->config->isStripeElementsEnabled()): ?>

    <?php echo $block->getLayout()->createBlock('StripeIntegration\Payments\Block\StripeElements')->toHtml(); ?>

  <?php else: ?>

    <div class="field required stripe-new">
      <label for="stripe_payments_cc_owner" class="label">
        <span><?php echo $block->escapeHtml(__('Name on Card')); ?></span>
      </label>
      <div>
        <input type="text" id="stripe_payments_cc_owner"
          <?php if (!$block->config->isStripeJsEnabled()): ?>
            name="payment[cc_owner]"
          <?php endif; ?>
          title="<?php echo $block->escapeHtml(__('Name on Card')); ?>" class="stripe-input"
          value="<?php /* @noEscape */ echo $block->getInfoData('cc_owner'); ?>" />
      </div>
    </div>

    <div class="field required stripe-new">
      <label for="stripe_payments_cc_number" class="label">
        <span><?php echo $block->escapeHtml(__('Card Number')); ?></span>
      </label>
      <div>
        <input type="text" id="stripe_payments_cc_number"
        <?php if (!$block->config->isStripeJsEnabled()): ?>
          name="payment[cc_number]"
        <?php endif; ?>
        title="<?php echo $block->escapeHtml(__('Card Number')); ?>" class="stripe-input" value="<?php /* @noEscape */ echo $block->getInfoData('cc_number'); ?>"/>
      </div>
    </div>

    <div class="field required stripe-new">
      <label for="stripe_payments_expiration_mo" class="label">
        <span><?php echo $block->escapeHtml(__('Expiration Date')); ?></span>
      </label>
      <div>
        <select id="stripe_payments_expiration_mo"
          <?php if (!$block->config->isStripeJsEnabled()): ?>
            name="payment[cc_exp_month]"
          <?php endif; ?>
          class="required-entry stripe-input">
          <?php foreach ($block->getCcMonths() as $k => $v): ?>
            <option value="<?php echo $block->escapeHtml($k); ?>"
              <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
              <?php echo $block->escapeHtml($v); ?>
            </option>
          <?php endforeach; ?>
        </select>
        <select id="stripe_payments_expiration_yr"
          <?php if (!$block->config->isStripeJsEnabled()): ?>
            name="payment[cc_exp_year]"
          <?php endif; ?>
          class="required-entry stripe-input">
          <?php foreach ($block->getCcYears() as $k => $v): ?>
            <option value="<?php /* @noEscape */ echo $k ? $block->escapeHtml($k) : '' ?>"
              <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
              <?php echo $block->escapeHtml($v); ?>
            </option>
          <?php endforeach ?>
        </select>
      </div>
    </div>

    <div class="field required stripe-new">
      <label for="stripe_payments_cc_cid" class="label">
        <span><?php echo $block->escapeHtml(__('Card Verification Number')); ?></span>
      </label>
      <div>
        <input type="text" title="<?php echo $block->escapeHtml(__('Card Verification Number')); ?>"
        class="required-entry stripe-input"
        style="max-width: 50px" id="stripe_payments_cc_cid"
        <?php if (!$block->config->isStripeJsEnabled()): ?>
          name="payment[cc_cid]"
        <?php endif; ?>
        value="<?php /* @noEscape */ echo $block->getInfoData('cc_cid') ?>"/>
      </div>
    </div>

  <?php endif; ?>

  </fieldset>

  <script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
      $(document).ready(function()
      {
        var securityMethod = '<?php echo $block->config->getSecurityMethod(); ?>';
        var stripeJsPublishableKey = '<?php echo $block->config->getPublishableKey(); ?>';
        stripe.avsFields = <?php echo $this->getBillingAddress(); ?>;
        if (securityMethod > 0)
          initStripe(stripeJsPublishableKey, securityMethod);
      });
    });
  </script>

  <div class="actions-toolbar">
    <div class="primary">
      <button type="submit" title="Save" class="action save primary"
        <?php if ($block->config->getSecurityMethod() > 0): ?>
          onclick="return stripe.saveCard(this);"
        <?php endif; ?>
        >
        <span>
          <?php echo $block->escapeHtml(__('Save')); ?>
        </span>
      </button>
    </div>
  </div>

</form>

<?php else: ?>

  <div class="message info empty">
    <span><?php echo $block->escapeHtml(__('You must first add a full billing address before you can add saved cards.')); ?></span>
  </div>

  </fieldset>
</form>
<?php endif; ?>
