<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Etsy
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Tier */
$element = $block->getElement();

?>
<?php $_htmlId      = 'requiredAttributes' ?>
<?php $_htmlClass   = 'requiredAttributeClass' ?>
<?php $_htmlName    = 'required_attributes' ?>
<?php $_readonly    = false ?>
<div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
     >
    <div class="control">
        <table class="admin__control-table tiers_table" id="tiers_table">
            <thead>
            <tr>
                <th class="col-customer-group"><?php /* @escapeNotVerified */ echo __('Etsy Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Magento Catalog Attribute') ?></th>
            </tr>
            </thead>
            <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
        </table>

        <script>
            require([
                'mage/template',
                "prototype",
                "mage/adminhtml/form"
            ], function (mageTemplate) {

//<![CDATA[
                var requiredAttributeRowTemplate = '<tr>'
                    + '<input type="hidden" value="0" name="<?php echo $_htmlName ?>[<%- data.index %>][required]" id="tier_price_row_<%- data.index %>_etsy_required"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][etsy_attribute_name]" id="tier_price_row_<%- data.index %>_etsy_attribute_hidden"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][etsy_attribute_type]" id="tier_price_row_<%- data.index %>_etsy_attribute_type"" />'
                    + '<td><select onclick="return requiredAttributeControl.setEtsyAttributeType(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][etsy_attribute_name]" id="tier_price_row_<%- data.index %>_etsy_attribute">'

                    <?php foreach ($this->getEtsyAttributes() as $optGroup) { 
                    $disable = '';
                    if($optGroup['label'] == 'Required Attributes'){
                        $disable = 'disabled="disabled"';
                    }
                    ?>
                    +'<optgroup <?php echo  $disable ?> label="<?php echo $optGroup['label'] ?> ">'
                    <?php
                    foreach ($optGroup['value'] as $_groupId => $_groupName): ?>
                    + '<option value="<?php echo $_groupName['etsy_attribute_name'] ?>" attribute_type="<?php echo $_groupName['etsy_attribute_type'] ?>"><?php echo __($_groupId) ?></option>'
                    <?php endforeach
                    ?>
                    +'</optgroup>'
                    <?php  }
                    ?>
                    + '</select></td>'
                    + '<td> <select class="<?php echo $_htmlClass ?> required_magento_attr required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][magento_attribute_code]" id="tier_price_row_<%- data.index %>_magento_attr">'
                    <?php foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                    + "<option value='<?php echo $_groupId ?>' ><?php echo __($_groupName) ?></option>"
                    <?php endforeach ?>
                    + '</select>'
                    + ' </td>'
                    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="tier_price_row_<%- data.index %>_delete" />'
                    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="tier_price_row_<%- data.index %>_delete_button" onclick="return requiredAttributeControl.deleteItem(event);">'
                    + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button></td>'
                    + '</tr>';

                var requiredAttributeControl = {
                    template: mageTemplate(requiredAttributeRowTemplate),
                    itemsCount: 0,
                    addItem : function () {
                        <?php if ($_readonly): ?>
                        if (arguments.length < 4) {
                            return;
                        }
                        <?php endif; ?>
                        var data = {
                            etsy_attribute: '',
                            magento_attr: '',
                            required: '',
                            etsy_attribute_type: '',
                            index: this.itemsCount++
                        };

                        if(arguments.length >= 4) {
                            data.etsy_attribute = arguments[0];
                            data.magento_attr      = arguments[1];
                            data.etsy_attribute_type      = arguments[2];
                            data.required        = arguments[3];
                        }
                        /*if (arguments.length == 5) {
                            data.readOnly = arguments[4];
                        }*/

                        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
                            bottom : this.template({
                                data: data
                            })
                        });
                        $('tier_price_row_' + data.index + '_etsy_attribute').value = data.etsy_attribute;
                        $('tier_price_row_' + data.index + '_magento_attr').value    = data.magento_attr;
                        $('tier_price_row_' + data.index + '_etsy_attribute_type').value    = data.etsy_attribute_type;


                        if(data.required==1) {
                            $('tier_price_row_' + data.index + '_delete_button').remove();
                            $('tier_price_row_' + data.index + '_etsy_attribute').disabled = true;
                            $('tier_price_row_' + data.index + '_etsy_attribute_hidden').value = data.etsy_attribute;
                            $('tier_price_row_' + data.index + '_etsy_required').value    = data.required;
                        }

                        if (data.readOnly == '1') {
                            ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                                $('tier_price_row_'+data.index+'_'+idx).disabled = true;
                            });
                            $('tier_price_row_'+data.index+'_delete_button').hide();
                        }

                        <?php if ($_readonly): ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                        <?php else: ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                        <?php endif; ?>
                    },
                    disableElement: function(el) {
                        el.disabled = true;
                        el.addClassName('disabled');
                    },
                    deleteItem: function(event) {
                        var tr = Event.findElement(event, 'tr');
                        if (tr) {
                            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                            Element.hide(tr);
                            Element.addClassName(tr, 'no-display template');
                        }
                        return false;
                    },
                    setEtsyAttributeType: function(e, index) {
                        var attributeType = e.options[e.selectedIndex].getAttribute('attribute_type');
                        $('tier_price_row_' + index + '_etsy_attribute_type').value    = attributeType;
                    }
                };
                <?php if(count($this->getMappedAttribute())>0)
                    foreach ($this->getMappedAttribute() as $_item): ?>

                requiredAttributeControl.addItem('<?php echo $_item['etsy_attribute_name'] ?>', '<?php echo $_item['magento_attribute_code'] ?>', '<?php echo $_item['etsy_attribute_type'] ?>','<?php echo $_item['required'] ?>' );
                <?php endforeach; ?>
                <?php if ($_readonly): ?>
                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
                    .each(requiredAttributeControl.disableElement);
                <?php endif; ?>

                window.requiredAttributeControl = requiredAttributeControl;
//]]>
            });
        </script>
    </div>
</div>